# Generated by Django 5.2.5 on 2025-10-20 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('horaInicio', models.TimeField(unique=True)),
                ('horaFin', models.TimeField()),
                ('capacidadMaxima', models.IntegerField()),
                ('capacidadActual', models.IntegerField()),
            ],
            options={
                'db_table': 'disponibilidadParque',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAcceso',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigoQR', models.ImageField(upload_to='')),
                ('fechaGeneracion', models.DateField()),
                ('rutVisitante', models.BooleanField()),
            ],
            options={
                'db_table': 'documentoAcceso',
            },
        ),
        migrations.CreateModel(
            name='EncargadoAcceso',
            fields=[
                ('idEncargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=11)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'encargadoAcceso',
            },
        ),
        migrations.CreateModel(
            name='SistemaNotificaciones',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEnvio', models.DateField()),
                ('tipo', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'sistemaNotificaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tarifa', models.IntegerField()),
            ],
            options={
                'db_table': 'tipoVisita',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=35)),
                ('edad', models.IntegerField()),
            ],
            options={
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadVisitantes', models.IntegerField()),
                ('estadoReserva', models.CharField(choices=[('ACTIVO', 'Activo'), ('UTILIZADO', 'Utilizado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=30)),
                ('fechaReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_fecha', to='ReservaSystemApp.disponibilidadparque', to_field='fecha')),
                ('horaReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_hora', to='ReservaSystemApp.disponibilidadparque', to_field='horaInicio')),
                ('tipoVisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.tipovisita', to_field='nombre')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.visitante')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('rutVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservaSystemApp.visitante')),
            ],
            options={
                'db_table': 'acompañante',
            },
        ),
    ]
