# Generated by Django 5.2.5 on 2025-11-22 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAcceso',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigoQR', models.ImageField(upload_to='')),
                ('fechaGeneracion', models.DateField()),
                ('rutVisitante', models.BooleanField()),
            ],
            options={
                'db_table': 'documentoAcceso',
            },
        ),
        migrations.CreateModel(
            name='EncargadoAcceso',
            fields=[
                ('idEncargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=11)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'encargadoAcceso',
            },
        ),
        migrations.CreateModel(
            name='SistemaNotificaciones',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEnvio', models.DateField()),
                ('tipo', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'sistemaNotificaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipoVisita',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('idVisitante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=35)),
                ('edad', models.IntegerField()),
            ],
            options={
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadParque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('capacidadMaxima', models.IntegerField()),
                ('capacidadActual', models.IntegerField()),
            ],
            options={
                'db_table': 'disponibilidadParque',
                'unique_together': {('fecha', 'horaInicio')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadVisitantes', models.IntegerField()),
                ('estadoReserva', models.CharField(choices=[('ACTIVO', 'Activo'), ('UTILIZADO', 'Utilizado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=30)),
                ('disponibilidad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.disponibilidadparque')),
                ('tipoVisita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.tipovisita')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.visitante')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='RegistroCambioReserva',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=50)),
                ('descripcionCambio', models.TextField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cambio', to='ReservaSystemApp.reserva')),
            ],
            options={
                'db_table': 'registroCambioReserva',
            },
        ),
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('idAcompañante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('rutVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservaSystemApp.visitante')),
            ],
            options={
                'db_table': 'acompañante',
            },
        ),
    ]
