# Generated by Django 5.2.5 on 2025-10-21 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fechaReserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horaReserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='disponibilidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.disponibilidadparque'),
        ),
        migrations.AlterField(
            model_name='disponibilidadparque',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disponibilidadparque',
            name='horaInicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidadparque',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadparque',
            unique_together={('fecha', 'horaInicio')},
        ),
    ]
