# Generated by Django 5.2.5 on 2025-11-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompañante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='edad',
        ),
        migrations.AddField(
            model_name='acompañante',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
