# Generated by Django 5.2.5 on 2025-10-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaSystemApp', '0002_remove_reserva_fechareserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovisita',
            name='tarifa',
        ),
    ]
