# Generated by Django 5.2.5 on 2025-10-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaSystemApp', '0003_remove_tipovisita_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipoVisita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ReservaSystemApp.tipovisita', to_field='nombre'),
        ),
    ]
