# Generated by Django 5.2.5 on 2025-11-19 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaSystemApp', '0004_alter_reserva_tipovisita'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCambioReserva',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=50)),
                ('descripcionCambio', models.TextField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cambio', to='ReservaSystemApp.reserva')),
            ],
            options={
                'db_table': 'registroCambioReserva',
            },
        ),
    ]
